name: Keep Alive

on:
  schedule:
    - cron: '55 */1 * * *'   # every 1h, at minute 55
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Empty commit
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: refresh"
          git push
